/**
 * WMO Weather interpretation codes (WW)
 * Maps Open-Meteo weather codes to rich UI metadata, icons, and atmospheric themes
 */

export const WEATHER_CODES = {
  0: {
    label: 'Clear sky',
    description: 'Cloudless, clear atmosphere',
    iconDay: 'clear-day',
    iconNight: 'clear-night',
    themeDay: 'theme-clear-day',
    themeNight: 'theme-clear-night',
    particle: 'sunbeams',
    particleNight: 'stars',
  },
  1: {
    label: 'Mainly clear',
    description: 'Mostly sunny with faint wisps',
    iconDay: 'partly-cloudy-day',
    iconNight: 'partly-cloudy-night',
    themeDay: 'theme-clear-day',
    themeNight: 'theme-clear-night',
    particle: 'sunbeams',
    particleNight: 'stars',
  },
  2: {
    label: 'Partly cloudy',
    description: 'Scattered clouds and pleasant breaks',
    iconDay: 'partly-cloudy-day',
    iconNight: 'partly-cloudy-night',
    themeDay: 'theme-cloudy-day',
    themeNight: 'theme-cloudy-night',
    particle: 'clouds',
    particleNight: 'clouds-night',
  },
  3: {
    label: 'Overcast',
    description: 'Uniform cloud cover dominating sky',
    iconDay: 'overcast',
    iconNight: 'overcast',
    themeDay: 'theme-overcast',
    themeNight: 'theme-overcast-night',
    particle: 'clouds',
    particleNight: 'clouds-night',
  },
  45: {
    label: 'Fog',
    description: 'Reduced visibility due to dense surface fog',
    iconDay: 'fog',
    iconNight: 'fog',
    themeDay: 'theme-fog',
    themeNight: 'theme-fog-night',
    particle: 'fog',
    particleNight: 'fog',
  },
  48: {
    label: 'Depositing rime fog',
    description: 'Icy mist depositing frost crystals',
    iconDay: 'fog',
    iconNight: 'fog',
    themeDay: 'theme-fog',
    themeNight: 'theme-fog-night',
    particle: 'fog',
    particleNight: 'fog',
  },
  51: {
    label: 'Light drizzle',
    description: 'Fine misting drizzle droplets',
    iconDay: 'drizzle',
    iconNight: 'drizzle',
    themeDay: 'theme-rain',
    themeNight: 'theme-rain-night',
    particle: 'drizzle',
    particleNight: 'drizzle',
  },
  53: {
    label: 'Moderate drizzle',
    description: 'Steady misting rain',
    iconDay: 'drizzle',
    iconNight: 'drizzle',
    themeDay: 'theme-rain',
    themeNight: 'theme-rain-night',
    particle: 'drizzle',
    particleNight: 'drizzle',
  },
  55: {
    label: 'Dense drizzle',
    description: 'Heavy saturation drizzle',
    iconDay: 'drizzle',
    iconNight: 'drizzle',
    themeDay: 'theme-rain',
    themeNight: 'theme-rain-night',
    particle: 'rain',
    particleNight: 'rain',
  },
  56: {
    label: 'Freezing drizzle',
    description: 'Sub-zero freezing mist drizzle',
    iconDay: 'freezing-rain',
    iconNight: 'freezing-rain',
    themeDay: 'theme-snow',
    themeNight: 'theme-snow-night',
    particle: 'snow',
    particleNight: 'snow',
  },
  57: {
    label: 'Dense freezing drizzle',
    description: 'Heavy freezing drizzle causing icy glaze',
    iconDay: 'freezing-rain',
    iconNight: 'freezing-rain',
    themeDay: 'theme-snow',
    themeNight: 'theme-snow-night',
    particle: 'snow',
    particleNight: 'snow',
  },
  61: {
    label: 'Slight rain',
    description: 'Gentle periodic rainfall',
    iconDay: 'rain',
    iconNight: 'rain',
    themeDay: 'theme-rain',
    themeNight: 'theme-rain-night',
    particle: 'rain',
    particleNight: 'rain',
  },
  63: {
    label: 'Moderate rain',
    description: 'Steady, consistent downpour',
    iconDay: 'rain',
    iconNight: 'rain',
    themeDay: 'theme-rain',
    themeNight: 'theme-rain-night',
    particle: 'rain',
    particleNight: 'rain',
  },
  65: {
    label: 'Heavy rain',
    description: 'Intense precipitation with strong runoff',
    iconDay: 'heavy-rain',
    iconNight: 'heavy-rain',
    themeDay: 'theme-heavy-rain',
    themeNight: 'theme-heavy-rain-night',
    particle: 'heavy-rain',
    particleNight: 'heavy-rain',
  },
  66: {
    label: 'Freezing rain',
    description: 'Cold rain freezing upon contact',
    iconDay: 'freezing-rain',
    iconNight: 'freezing-rain',
    themeDay: 'theme-snow',
    themeNight: 'theme-snow-night',
    particle: 'snow',
    particleNight: 'snow',
  },
  67: {
    label: 'Heavy freezing rain',
    description: 'Dangerous freezing glaze rain',
    iconDay: 'freezing-rain',
    iconNight: 'freezing-rain',
    themeDay: 'theme-snow',
    themeNight: 'theme-snow-night',
    particle: 'snow',
    particleNight: 'snow',
  },
  71: {
    label: 'Slight snow fall',
    description: 'Gentle floating snowflakes',
    iconDay: 'snow',
    iconNight: 'snow',
    themeDay: 'theme-snow',
    themeNight: 'theme-snow-night',
    particle: 'snow',
    particleNight: 'snow',
  },
  73: {
    label: 'Moderate snow fall',
    description: 'Steady accumulation of snowfall',
    iconDay: 'snow',
    iconNight: 'snow',
    themeDay: 'theme-snow',
    themeNight: 'theme-snow-night',
    particle: 'snow',
    particleNight: 'snow',
  },
  75: {
    label: 'Heavy snow fall',
    description: 'Thick blizzard-like snowfall',
    iconDay: 'heavy-snow',
    iconNight: 'heavy-snow',
    themeDay: 'theme-snow',
    themeNight: 'theme-snow-night',
    particle: 'heavy-snow',
    particleNight: 'heavy-snow',
  },
  77: {
    label: 'Snow grains',
    description: 'Fine frozen pellets drifting down',
    iconDay: 'snow',
    iconNight: 'snow',
    themeDay: 'theme-snow',
    themeNight: 'theme-snow-night',
    particle: 'snow',
    particleNight: 'snow',
  },
  80: {
    label: 'Slight rain showers',
    description: 'Passing brief rain showers',
    iconDay: 'showers',
    iconNight: 'showers',
    themeDay: 'theme-rain',
    themeNight: 'theme-rain-night',
    particle: 'rain',
    particleNight: 'rain',
  },
  81: {
    label: 'Moderate rain showers',
    description: 'Lively passing showers',
    iconDay: 'showers',
    iconNight: 'showers',
    themeDay: 'theme-rain',
    themeNight: 'theme-rain-night',
    particle: 'rain',
    particleNight: 'rain',
  },
  82: {
    label: 'Violent rain showers',
    description: 'Torrential convective deluge',
    iconDay: 'heavy-rain',
    iconNight: 'heavy-rain',
    themeDay: 'theme-heavy-rain',
    themeNight: 'theme-heavy-rain-night',
    particle: 'heavy-rain',
    particleNight: 'heavy-rain',
  },
  85: {
    label: 'Slight snow showers',
    description: 'Scattered brief snow flurries',
    iconDay: 'snow',
    iconNight: 'snow',
    themeDay: 'theme-snow',
    themeNight: 'theme-snow-night',
    particle: 'snow',
    particleNight: 'snow',
  },
  86: {
    label: 'Heavy snow showers',
    description: 'Gusty bursts of heavy snow flurries',
    iconDay: 'heavy-snow',
    iconNight: 'heavy-snow',
    themeDay: 'theme-snow',
    themeNight: 'theme-snow-night',
    particle: 'heavy-snow',
    particleNight: 'heavy-snow',
  },
  95: {
    label: 'Thunderstorm',
    description: 'Atmospheric storm with lightning activity',
    iconDay: 'thunderstorm',
    iconNight: 'thunderstorm',
    themeDay: 'theme-storm',
    themeNight: 'theme-storm-night',
    particle: 'storm',
    particleNight: 'storm',
  },
  96: {
    label: 'Thunderstorm with slight hail',
    description: 'Electric storm with small ice pellets',
    iconDay: 'thunderstorm',
    iconNight: 'thunderstorm',
    themeDay: 'theme-storm',
    themeNight: 'theme-storm-night',
    particle: 'storm',
    particleNight: 'storm',
  },
  99: {
    label: 'Thunderstorm with heavy hail',
    description: 'Severe thunderstorm with destructive hail',
    iconDay: 'thunderstorm',
    iconNight: 'thunderstorm',
    themeDay: 'theme-storm',
    themeNight: 'theme-storm-night',
    particle: 'storm',
    particleNight: 'storm',
  }
};

/**
 * Returns weather metadata for a specific WMO code
 */
export function getWeatherMeta(code, isDay = 1) {
  const meta = WEATHER_CODES[code] || WEATHER_CODES[0];
  return {
    code,
    label: meta.label,
    description: meta.description,
    icon: isDay ? meta.iconDay : meta.iconNight,
    theme: isDay ? meta.themeDay : meta.themeNight,
    particle: isDay ? meta.particle : meta.particleNight,
    isDay: Boolean(isDay),
  };
}
